services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    working_dir: /workspace/silentspeechoe
    volumes:
      - ..:/workspace/silentspeechoe:cached
    environment:
      PYTHONPATH: /workspace/silentspeechoe/src
    shm_size: "8gb"
    tty: true
