defaults:
  - _self_
  - data: openearable
  - experiment: whisper_to_silent
  - model: fusion_cnn
  - train: default

hydra:
  run:
    dir: outputs/runs/${experiment.name}/${model.name}_${train.input_type}
  job:
    chdir: true

project:
  name: silentspeechoe
  task: closed_set_sentence_recognition
  framework: pytorch
