"""Evaluate ArcFace IMU authentication templates on query feature samples."""

from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score, roc_curve

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from silentspeechoe.evaluation.metrics import (  # noqa: E402
    compute_authentication_metrics,
    compute_classification_metrics,
)
from silentspeechoe.models.imu_mlp import IMUMLPArcFace  # noqa: E402


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate ArcFace IMU templates on semantic query samples."
    )
    parser.add_argument(
        "--templates",
        default=(
            "outputs/close_set_evaluation/"
            "imu_mlp_arcface_normal_silent_whisper_noisy_nonsemantic/"
            "templates.pt"
        ),
        help="Template .pt file generated by generate_imu_arcface_templates.py.",
    )
    parser.add_argument(
        "--query-feature-dir",
        default=(
            "data/processed/features/"
            "imu_te_binaural_lrdiff_200hz_raw9_gaussian_noise_005"
        ),
        help="Feature directory containing query samples.",
    )
    parser.add_argument(
        "--out",
        default=(
            "outputs/close_set_evaluation/"
            "imu_mlp_arcface_normal_silent_whisper_noisy_nonsemantic/"
            "semantic_query_metrics.json"
        ),
        help="Output JSON metrics path.",
    )
    parser.add_argument(
        "--sentence-type",
        default="semantic",
        help="Query sentence type.",
    )
    parser.add_argument(
        "--domains",
        nargs="+",
        default=["normal", "whisper", "silent"],
        help="Query domains.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=256,
        help="Embedding extraction batch size.",
    )
    parser.add_argument(
        "--device",
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Device for embedding extraction.",
    )
    parser.add_argument(
        "--far-target",
        type=float,
        default=0.01,
        help="FAR operating point for FRR@FAR reporting.",
    )
    parser.add_argument(
        "--dev-sentences-per-subject",
        type=int,
        default=None,
        help=(
            "If set, randomly select this many sentence_id values per subject "
            "as a semantic dev set for threshold selection. Remaining query "
            "sentences are evaluated as the test set."
        ),
    )
    parser.add_argument(
        "--split-seed",
        type=int,
        default=42,
        help="Random seed for semantic dev/test sentence splitting.",
    )
    parser.add_argument(
        "--domain-specific-thresholds",
        action="store_true",
        help=(
            "When using a semantic dev/test split, select separate one-vs-all "
            "thresholds for each query domain instead of pooling all domains."
        ),
    )
    parser.add_argument(
        "--global-threshold",
        action="store_true",
        help=(
            "When using a semantic dev/test split, select one shared pairwise "
            "authentication threshold for all subjects."
        ),
    )
    return parser.parse_args(argv)


def _resolve_project_path(path_value: str | Path) -> Path:
    path = Path(path_value)
    if path.is_absolute():
        return path
    return _PROJECT_ROOT / path


def _load_manifest(feature_dir: Path) -> dict:
    manifest_path = feature_dir / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    with manifest_path.open("r") as f:
        return json.load(f)


def _filter_records(
    records: list[dict],
    *,
    sentence_type: str,
    domains: set[str],
    subject_ids: set[str],
) -> list[dict]:
    return [
        record
        for record in records
        if record.get("sentence_type") == sentence_type
        and record.get("domain") in domains
        and str(record.get("subject_id")) in subject_ids
    ]


def _load_feature_matrix(feature_dir: Path, records: list[dict]) -> torch.Tensor:
    features = []
    for record in records:
        sample = torch.load(
            feature_dir / record["file"],
            map_location="cpu",
            weights_only=True,
        )
        features.append(sample["x"].float())
    if not features:
        raise ValueError("No query records selected for template evaluation")
    return torch.stack(features, dim=0)


def _build_model_from_checkpoint(checkpoint: dict) -> IMUMLPArcFace:
    state = checkpoint["full_model_state_dict"]
    fc1_weight = state["fc1.weight"]
    fc2_weight = state["fc2.weight"]
    classifier_weight = state["classifier.weight"]
    model = IMUMLPArcFace(
        in_features=int(fc1_weight.shape[1]),
        hidden1=int(fc1_weight.shape[0]),
        hidden2=int(fc2_weight.shape[0]),
        num_classes=int(classifier_weight.shape[0]),
    )
    model.load_state_dict(state, strict=True)
    return model


@torch.no_grad()
def _extract_embeddings(
    model: IMUMLPArcFace,
    x: torch.Tensor,
    *,
    mean: torch.Tensor,
    std: torch.Tensor,
    batch_size: int,
    device: torch.device,
) -> torch.Tensor:
    model.eval()
    model.to(device)
    mean = mean.to(device)
    std = std.to(device)

    embeddings = []
    for start in range(0, x.shape[0], batch_size):
        batch = x[start : start + batch_size].to(device)
        batch = (batch - mean) / std
        emb = model.extract_features(batch)
        emb = F.normalize(emb, dim=1)
        embeddings.append(emb.cpu())
    return torch.cat(embeddings, dim=0)


def _metrics_to_jsonable(value):
    if isinstance(value, dict):
        return {str(k): _metrics_to_jsonable(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_metrics_to_jsonable(v) for v in value]
    if isinstance(value, tuple):
        return [_metrics_to_jsonable(v) for v in value]
    if isinstance(value, np.ndarray):
        return _metrics_to_jsonable(value.tolist())
    if isinstance(value, np.generic):
        return _metrics_to_jsonable(value.item())
    if isinstance(value, (float, int, str, bool)) or value is None:
        if isinstance(value, float) and not np.isfinite(value):
            return None
        return value
    return float(value)


def _compact_metrics_row(name: str, metrics: dict) -> dict[str, float | str]:
    """Return one table row with the main authentication metrics."""
    keys = (
        "accuracy",
        "macro_f1",
        "balanced_accuracy",
        "top3_accuracy",
        "eer",
        "roc_auc",
        "far",
        "frr",
        "frr_at_far_1pct",
    )
    row: dict[str, float | str] = {"split": name}
    for key in keys:
        if key in metrics:
            row[key] = float(metrics[key])
    return row


def _write_summary_files(
    out_path: Path,
    *,
    overall_metrics: dict,
    by_domain: dict[str, dict],
) -> tuple[Path, Path]:
    """Write compact overall + per-domain summary files next to out_path."""
    domain_order = ["normal", "whisper", "silent"]
    rows = [_compact_metrics_row("overall", overall_metrics)]
    for domain in domain_order:
        if domain in by_domain:
            rows.append(_compact_metrics_row(domain, by_domain[domain]))
    for domain in sorted(set(by_domain) - set(domain_order)):
        rows.append(_compact_metrics_row(domain, by_domain[domain]))

    summary_json_path = out_path.with_name(f"{out_path.stem}_summary.json")
    summary_csv_path = out_path.with_name(f"{out_path.stem}_summary.csv")

    with summary_json_path.open("w") as f:
        json.dump({"rows": rows}, f, indent=2)

    fieldnames = [
        "split",
        "accuracy",
        "macro_f1",
        "balanced_accuracy",
        "top3_accuracy",
        "eer",
        "roc_auc",
        "far",
        "frr",
        "frr_at_far_1pct",
    ]
    with summary_csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    return summary_json_path, summary_csv_path


def _sentence_id_sort_key(sentence_id: str) -> tuple:
    prefix, _, suffix = sentence_id.rpartition("_")
    sentence_number = int(suffix) if suffix.isdigit() else -1
    return prefix, sentence_number, sentence_id


def _split_dev_test_by_subject_sentence(
    records: list[dict],
    *,
    dev_sentences_per_subject: int,
    seed: int,
) -> tuple[list[int], list[int], dict[str, list[str]]]:
    """Split records by subject-level sentence IDs for threshold tuning."""
    if dev_sentences_per_subject <= 0:
        raise ValueError(
            "dev-sentences-per-subject must be positive when provided, got "
            f"{dev_sentences_per_subject}"
        )

    by_subject_sentence: dict[str, dict[str, list[int]]] = {}
    for index, record in enumerate(records):
        subject_id = str(record["subject_id"])
        sentence_id = str(record.get("sentence_id", ""))
        by_subject_sentence.setdefault(subject_id, {}).setdefault(sentence_id, [])
        by_subject_sentence[subject_id][sentence_id].append(index)

    rng = random.Random(seed)
    dev_indices: list[int] = []
    test_indices: list[int] = []
    selected_sentence_ids: dict[str, list[str]] = {}

    for subject_id in sorted(by_subject_sentence):
        sentence_ids = sorted(
            by_subject_sentence[subject_id],
            key=_sentence_id_sort_key,
        )
        if len(sentence_ids) <= dev_sentences_per_subject:
            raise ValueError(
                f"Subject {subject_id} has {len(sentence_ids)} sentence_id values; "
                f"need more than {dev_sentences_per_subject} for dev/test split"
            )

        shuffled = list(sentence_ids)
        rng.shuffle(shuffled)
        selected = sorted(
            shuffled[:dev_sentences_per_subject],
            key=_sentence_id_sort_key,
        )
        selected_set = set(selected)
        selected_sentence_ids[subject_id] = selected

        for sentence_id in sentence_ids:
            target = dev_indices if sentence_id in selected_set else test_indices
            target.extend(by_subject_sentence[subject_id][sentence_id])

    return sorted(dev_indices), sorted(test_indices), selected_sentence_ids


def _as_numpy_1d(value, name: str) -> np.ndarray:
    if torch.is_tensor(value):
        value = value.detach().cpu().numpy()
    array = np.asarray(value)
    if array.ndim != 1:
        raise ValueError(f"{name} must be 1-D, got shape {array.shape}")
    return array


def _as_numpy_2d(value, name: str) -> np.ndarray:
    if torch.is_tensor(value):
        value = value.detach().cpu().numpy()
    array = np.asarray(value)
    if array.ndim != 2:
        raise ValueError(f"{name} must be 2-D, got shape {array.shape}")
    return array


def _binary_rates_at_threshold(
    y_binary: np.ndarray,
    score: np.ndarray,
    threshold: float,
) -> dict[str, float]:
    accept = score >= threshold
    return _binary_rates_from_accept(y_binary, accept)


def _binary_rates_from_accept(
    y_binary: np.ndarray,
    accept: np.ndarray,
) -> dict[str, float]:
    positives = y_binary == 1
    negatives = ~positives

    true_accept = int(np.sum(accept & positives))
    false_reject = int(np.sum((~accept) & positives))
    false_accept = int(np.sum(accept & negatives))
    true_reject = int(np.sum((~accept) & negatives))

    num_positive = true_accept + false_reject
    num_negative = false_accept + true_reject
    if num_positive == 0 or num_negative == 0:
        raise ValueError("Authentication metrics require positives and negatives")

    return {
        "accuracy": float((true_accept + true_reject) / y_binary.shape[0]),
        "far": float(false_accept / num_negative),
        "frr": float(false_reject / num_positive),
        "true_accept": float(true_accept),
        "false_reject": float(false_reject),
        "false_accept": float(false_accept),
        "true_reject": float(true_reject),
        "num_positive": float(num_positive),
        "num_negative": float(num_negative),
    }


def _select_dev_thresholds(
    y_true,
    y_score,
    *,
    far_target: float,
) -> dict:
    """Select one-vs-all thresholds from the semantic dev split."""
    y_true_np = _as_numpy_1d(y_true, "y_true").astype(np.int64)
    scores_np = _as_numpy_2d(y_score, "y_score").astype(np.float64)
    num_subjects = scores_np.shape[1]

    eer_thresholds: dict[str, float] = {}
    far_target_thresholds: dict[str, float] = {}
    by_subject: dict[str, dict[str, float]] = {}

    for subject_index in range(num_subjects):
        y_binary = (y_true_np == subject_index).astype(np.int64)
        if y_binary.sum() == 0 or y_binary.sum() == y_binary.shape[0]:
            continue

        subject_scores = scores_np[:, subject_index]
        fpr, tpr, thresholds = roc_curve(y_binary, subject_scores)
        frr_curve = 1.0 - tpr

        eer_index = int(np.argmin(np.abs(fpr - frr_curve)))
        eer_threshold = float(thresholds[eer_index])
        eer_rates = _binary_rates_at_threshold(
            y_binary,
            subject_scores,
            eer_threshold,
        )

        eligible = np.flatnonzero(fpr <= far_target)
        if eligible.size == 0:
            far_index = 0
        else:
            far_index = int(eligible[np.argmax(tpr[eligible])])
        far_threshold = float(thresholds[far_index])
        far_rates = _binary_rates_at_threshold(
            y_binary,
            subject_scores,
            far_threshold,
        )

        key = str(subject_index)
        eer_thresholds[key] = eer_threshold
        far_target_thresholds[key] = far_threshold
        by_subject[key] = {
            "eer_threshold": eer_threshold,
            "eer_far": eer_rates["far"],
            "eer_frr": eer_rates["frr"],
            "eer_accuracy": eer_rates["accuracy"],
            "far_target_threshold": far_threshold,
            "far_target_far": far_rates["far"],
            "far_target_frr": far_rates["frr"],
            "far_target_accuracy": far_rates["accuracy"],
            "roc_auc": float(roc_auc_score(y_binary, subject_scores)),
            "num_positive": float(y_binary.sum()),
            "num_negative": float(y_binary.shape[0] - y_binary.sum()),
        }

    if not by_subject:
        raise ValueError("No valid subjects for dev threshold selection")

    return {
        "far_target": float(far_target),
        "eer_thresholds": eer_thresholds,
        "far_target_thresholds": far_target_thresholds,
        "by_subject": by_subject,
    }


def _fixed_threshold_metrics(
    y_true,
    y_score,
    *,
    thresholds: dict[str, float],
    far_target: float,
    threshold_name: str,
    include_frr_at_far: bool,
) -> dict:
    """Evaluate one-vs-all authentication with externally selected thresholds."""
    y_true_np = _as_numpy_1d(y_true, "y_true").astype(np.int64)
    scores_np = _as_numpy_2d(y_score, "y_score").astype(np.float64)
    y_pred = np.argmax(scores_np, axis=1)

    identification = compute_classification_metrics(
        y_true_np,
        y_pred,
        scores_np,
        top_k=3,
    )
    swept_metrics = compute_authentication_metrics(
        y_true_np,
        scores_np,
        far_target=far_target,
    )

    by_subject: dict[str, dict[str, float]] = {}
    for subject_key, threshold in thresholds.items():
        subject_index = int(subject_key)
        if subject_index < 0 or subject_index >= scores_np.shape[1]:
            continue

        y_binary = (y_true_np == subject_index).astype(np.int64)
        if y_binary.sum() == 0 or y_binary.sum() == y_binary.shape[0]:
            continue

        subject_scores = scores_np[:, subject_index]
        rates = _binary_rates_at_threshold(y_binary, subject_scores, threshold)
        by_subject[subject_key] = {
            "threshold": float(threshold),
            "accuracy": rates["accuracy"],
            "far": rates["far"],
            "frr": rates["frr"],
            "roc_auc": float(roc_auc_score(y_binary, subject_scores)),
            "num_positive": rates["num_positive"],
            "num_negative": rates["num_negative"],
        }

    if not by_subject:
        raise ValueError("No valid subjects for fixed-threshold authentication")

    authentication = {
        "threshold_source": "semantic_dev",
        "threshold_name": threshold_name,
        "far_target": float(far_target),
        "num_subjects": float(len(by_subject)),
        "accuracy": float(np.mean([m["accuracy"] for m in by_subject.values()])),
        "far": float(np.mean([m["far"] for m in by_subject.values()])),
        "frr": float(np.mean([m["frr"] for m in by_subject.values()])),
        "roc_auc": float(np.mean([m["roc_auc"] for m in by_subject.values()])),
    }

    result: dict = {
        **identification,
        "roc_auc": authentication["roc_auc"],
        "eer": float(swept_metrics["eer"]),
        "far": authentication["far"],
        "frr": authentication["frr"],
        "authentication_accuracy": authentication["accuracy"],
        "far_at_far_target": authentication["far"],
        "frr_at_far_target": authentication["frr"],
        "threshold_source": "semantic_dev",
        "threshold_name": threshold_name,
        "authentication": authentication,
        "by_subject": by_subject,
        "swept_reference": {
            "eer": float(swept_metrics["eer"]),
            "far": float(swept_metrics["far"]),
            "frr": float(swept_metrics["frr"]),
            "frr_at_far_target": float(swept_metrics["frr_at_far_target"]),
        },
    }
    if include_frr_at_far and np.isclose(far_target, 0.01):
        result["frr_at_far_1pct"] = authentication["frr"]
    return result


def _compute_by_domain_fixed_metrics(
    records: list[dict],
    indices: list[int],
    y_true,
    scores,
    *,
    thresholds: dict[str, float],
    far_target: float,
    threshold_name: str,
    include_frr_at_far: bool,
) -> dict[str, dict]:
    by_domain = {}
    for domain in sorted({records[index]["domain"] for index in indices}):
        domain_positions = [
            position
            for position, record_index in enumerate(indices)
            if records[record_index].get("domain") == domain
        ]
        domain_y = y_true[domain_positions]
        domain_scores = scores[domain_positions]
        by_domain[domain] = _fixed_threshold_metrics(
            domain_y,
            domain_scores,
            thresholds=thresholds,
            far_target=far_target,
            threshold_name=threshold_name,
            include_frr_at_far=include_frr_at_far,
        )
    return by_domain


def _global_binary_pairs(y_true, y_score) -> tuple[np.ndarray, np.ndarray]:
    """Flatten all query-template scores into genuine/impostor pairs."""
    y_true_np = _as_numpy_1d(y_true, "y_true").astype(np.int64)
    scores_np = _as_numpy_2d(y_score, "y_score").astype(np.float64)
    class_indices = np.arange(scores_np.shape[1], dtype=np.int64)[None, :]
    genuine = class_indices == y_true_np[:, None]
    return genuine.astype(np.int64).reshape(-1), scores_np.reshape(-1)


def _global_swept_metrics(y_true, y_score, *, far_target: float) -> dict[str, float]:
    """Compute pairwise global authentication metrics over all subjects."""
    y_binary, pair_scores = _global_binary_pairs(y_true, y_score)
    if y_binary.sum() == 0 or y_binary.sum() == y_binary.shape[0]:
        raise ValueError("Global authentication metrics require both pair classes")

    fpr, tpr, thresholds = roc_curve(y_binary, pair_scores)
    frr_curve = 1.0 - tpr

    eer_index = int(np.argmin(np.abs(fpr - frr_curve)))
    eer_threshold = float(thresholds[eer_index])
    eer_rates = _binary_rates_at_threshold(
        y_binary,
        pair_scores,
        eer_threshold,
    )

    eligible = np.flatnonzero(fpr <= far_target)
    if eligible.size == 0:
        far_index = 0
    else:
        far_index = int(eligible[np.argmax(tpr[eligible])])
    far_threshold = float(thresholds[far_index])
    far_rates = _binary_rates_at_threshold(
        y_binary,
        pair_scores,
        far_threshold,
    )

    return {
        "roc_auc": float(roc_auc_score(y_binary, pair_scores)),
        "eer": float((fpr[eer_index] + frr_curve[eer_index]) / 2.0),
        "eer_threshold": eer_threshold,
        "eer_far": eer_rates["far"],
        "eer_frr": eer_rates["frr"],
        "eer_accuracy": eer_rates["accuracy"],
        "far_target": float(far_target),
        "far_target_threshold": far_threshold,
        "far_at_far_target": far_rates["far"],
        "frr_at_far_target": far_rates["frr"],
        "far_target_accuracy": far_rates["accuracy"],
        "num_positive": float(y_binary.sum()),
        "num_negative": float(y_binary.shape[0] - y_binary.sum()),
    }


def _global_fixed_threshold_metrics(
    y_true,
    y_score,
    *,
    threshold: float,
    far_target: float,
    threshold_name: str,
) -> dict:
    """Evaluate authentication using one global threshold."""
    y_true_np = _as_numpy_1d(y_true, "y_true").astype(np.int64)
    scores_np = _as_numpy_2d(y_score, "y_score").astype(np.float64)
    y_pred = np.argmax(scores_np, axis=1)
    identification = compute_classification_metrics(
        y_true_np,
        y_pred,
        scores_np,
        top_k=3,
    )

    y_binary, pair_scores = _global_binary_pairs(y_true_np, scores_np)
    rates = _binary_rates_at_threshold(y_binary, pair_scores, threshold)
    swept_metrics = _global_swept_metrics(
        y_true_np,
        scores_np,
        far_target=far_target,
    )

    authentication = {
        "threshold_source": "semantic_dev_global",
        "threshold_name": threshold_name,
        "threshold": float(threshold),
        "far_target": float(far_target),
        "accuracy": rates["accuracy"],
        "far": rates["far"],
        "frr": rates["frr"],
        "roc_auc": swept_metrics["roc_auc"],
        "num_positive": rates["num_positive"],
        "num_negative": rates["num_negative"],
    }

    result = {
        **identification,
        "roc_auc": swept_metrics["roc_auc"],
        "eer": swept_metrics["eer"],
        "far": rates["far"],
        "frr": rates["frr"],
        "authentication_accuracy": rates["accuracy"],
        "far_at_far_target": rates["far"],
        "frr_at_far_target": rates["frr"],
        "threshold_source": "semantic_dev_global",
        "threshold_name": threshold_name,
        "threshold": float(threshold),
        "authentication": authentication,
        "swept_reference": swept_metrics,
    }
    if np.isclose(far_target, 0.01):
        result["frr_at_far_1pct"] = rates["frr"]
    return result


def _compute_by_domain_global_fixed_metrics(
    records: list[dict],
    indices: list[int],
    y_true,
    scores,
    *,
    threshold: float,
    far_target: float,
    threshold_name: str,
) -> dict[str, dict]:
    by_domain = {}
    for domain in sorted({records[index]["domain"] for index in indices}):
        domain_positions = _domain_positions(records, indices, domain)
        domain_y = y_true[domain_positions]
        domain_scores = scores[domain_positions]
        by_domain[domain] = _global_fixed_threshold_metrics(
            domain_y,
            domain_scores,
            threshold=threshold,
            far_target=far_target,
            threshold_name=threshold_name,
        )
    return by_domain


def _fixed_domain_specific_threshold_metrics(
    records: list[dict],
    indices: list[int],
    y_true,
    y_score,
    *,
    thresholds_by_domain: dict[str, dict[str, float]],
    far_target: float,
    threshold_name: str,
    include_frr_at_far: bool,
) -> dict:
    """Evaluate pooled test samples with domain-specific thresholds."""
    y_true_np = _as_numpy_1d(y_true, "y_true").astype(np.int64)
    scores_np = _as_numpy_2d(y_score, "y_score").astype(np.float64)
    y_pred = np.argmax(scores_np, axis=1)

    identification = compute_classification_metrics(
        y_true_np,
        y_pred,
        scores_np,
        top_k=3,
    )
    swept_metrics = compute_authentication_metrics(
        y_true_np,
        scores_np,
        far_target=far_target,
    )

    domains = [str(records[index]["domain"]) for index in indices]
    by_subject: dict[str, dict[str, float | dict[str, float]]] = {}
    for subject_index in range(scores_np.shape[1]):
        threshold_values = []
        missing_domains = []
        for domain in domains:
            subject_thresholds = thresholds_by_domain.get(domain, {})
            threshold = subject_thresholds.get(str(subject_index))
            if threshold is None:
                missing_domains.append(domain)
                threshold_values.append(np.inf)
            else:
                threshold_values.append(float(threshold))

        if missing_domains:
            unique_missing = sorted(set(missing_domains))
            raise ValueError(
                f"Missing thresholds for subject {subject_index} in domains "
                f"{unique_missing}"
            )

        y_binary = (y_true_np == subject_index).astype(np.int64)
        if y_binary.sum() == 0 or y_binary.sum() == y_binary.shape[0]:
            continue

        threshold_array = np.asarray(threshold_values, dtype=np.float64)
        subject_scores = scores_np[:, subject_index]
        accept = subject_scores >= threshold_array
        rates = _binary_rates_from_accept(y_binary, accept)
        by_subject[str(subject_index)] = {
            "thresholds_by_domain": {
                domain: float(thresholds_by_domain[domain][str(subject_index)])
                for domain in sorted(thresholds_by_domain)
            },
            "accuracy": rates["accuracy"],
            "far": rates["far"],
            "frr": rates["frr"],
            "roc_auc": float(roc_auc_score(y_binary, subject_scores)),
            "num_positive": rates["num_positive"],
            "num_negative": rates["num_negative"],
        }

    if not by_subject:
        raise ValueError("No valid subjects for domain-specific authentication")

    authentication = {
        "threshold_source": "semantic_dev_by_domain",
        "threshold_name": threshold_name,
        "far_target": float(far_target),
        "num_subjects": float(len(by_subject)),
        "accuracy": float(np.mean([m["accuracy"] for m in by_subject.values()])),
        "far": float(np.mean([m["far"] for m in by_subject.values()])),
        "frr": float(np.mean([m["frr"] for m in by_subject.values()])),
        "roc_auc": float(np.mean([m["roc_auc"] for m in by_subject.values()])),
    }

    result: dict = {
        **identification,
        "roc_auc": authentication["roc_auc"],
        "eer": float(swept_metrics["eer"]),
        "far": authentication["far"],
        "frr": authentication["frr"],
        "authentication_accuracy": authentication["accuracy"],
        "far_at_far_target": authentication["far"],
        "frr_at_far_target": authentication["frr"],
        "threshold_source": "semantic_dev_by_domain",
        "threshold_name": threshold_name,
        "authentication": authentication,
        "by_subject": by_subject,
        "swept_reference": {
            "eer": float(swept_metrics["eer"]),
            "far": float(swept_metrics["far"]),
            "frr": float(swept_metrics["frr"]),
            "frr_at_far_target": float(swept_metrics["frr_at_far_target"]),
        },
    }
    if include_frr_at_far and np.isclose(far_target, 0.01):
        result["frr_at_far_1pct"] = authentication["frr"]
    return result


def _domain_positions(
    records: list[dict],
    indices: list[int],
    domain: str,
) -> list[int]:
    return [
        position
        for position, record_index in enumerate(indices)
        if records[record_index].get("domain") == domain
    ]


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)
    domains = set(args.domains)
    if args.batch_size <= 0:
        raise ValueError(f"batch-size must be positive, got {args.batch_size}")

    templates_path = _resolve_project_path(args.templates)
    query_feature_dir = _resolve_project_path(args.query_feature_dir)
    out_path = _resolve_project_path(args.out)

    template_payload = torch.load(
        templates_path,
        map_location="cpu",
        weights_only=False,
    )
    templates = template_payload["templates"].float()
    subject_ids = [str(subject_id) for subject_id in template_payload["subject_ids"]]
    subject_to_index = {
        str(subject_id): int(index)
        for subject_id, index in template_payload["subject_to_index"].items()
    }

    encoder_checkpoint = torch.load(
        template_payload["encoder_checkpoint"],
        map_location="cpu",
        weights_only=False,
    )
    model = _build_model_from_checkpoint(encoder_checkpoint)

    query_manifest = _load_manifest(query_feature_dir)
    query_records = _filter_records(
        query_manifest["records"],
        sentence_type=args.sentence_type,
        domains=domains,
        subject_ids=set(subject_ids),
    )
    x = _load_feature_matrix(query_feature_dir, query_records)

    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but torch.cuda.is_available() is false")

    embeddings = _extract_embeddings(
        model,
        x,
        mean=template_payload["feature_mean"].float(),
        std=template_payload["feature_std"].float(),
        batch_size=args.batch_size,
        device=device,
    )
    templates = F.normalize(templates, dim=1)
    scores = embeddings @ templates.T
    y_true = torch.tensor(
        [subject_to_index[str(record["subject_id"])] for record in query_records],
        dtype=torch.long,
    )

    overall_metrics = compute_authentication_metrics(
        y_true,
        scores,
        far_target=args.far_target,
    )

    by_domain = {}
    for domain in sorted({record["domain"] for record in query_records}):
        indices = [
            index
            for index, record in enumerate(query_records)
            if record.get("domain") == domain
        ]
        domain_y = y_true[indices]
        domain_scores = scores[indices]
        by_domain[domain] = compute_authentication_metrics(
            domain_y,
            domain_scores,
            far_target=args.far_target,
        )

    metrics = {
        "template_file": str(templates_path),
        "query_feature_dir": str(query_feature_dir),
        "sentence_type": args.sentence_type,
        "domains": sorted(domains),
        "num_query_samples": len(query_records),
        "num_subjects": len(subject_ids),
        "embedding_dim": int(embeddings.shape[1]),
        "score_type": "cosine_similarity_query_embedding_to_template",
        "far_target": float(args.far_target),
        "overall": _metrics_to_jsonable(overall_metrics),
        "by_domain": _metrics_to_jsonable(by_domain),
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        json.dump(metrics, f, indent=2)
    summary_json_path, summary_csv_path = _write_summary_files(
        out_path,
        overall_metrics=overall_metrics,
        by_domain=by_domain,
    )

    dev_test_result = None
    domain_specific_result = None
    global_threshold_result = None
    if args.dev_sentences_per_subject is not None:
        dev_indices, test_indices, selected_dev_sentence_ids = (
            _split_dev_test_by_subject_sentence(
                query_records,
                dev_sentences_per_subject=args.dev_sentences_per_subject,
                seed=args.split_seed,
            )
        )
        dev_y = y_true[dev_indices]
        dev_scores = scores[dev_indices]
        test_y = y_true[test_indices]
        test_scores = scores[test_indices]

        dev_thresholds = _select_dev_thresholds(
            dev_y,
            dev_scores,
            far_target=args.far_target,
        )
        dev_swept_metrics = compute_authentication_metrics(
            dev_y,
            dev_scores,
            far_target=args.far_target,
        )
        test_swept_metrics = compute_authentication_metrics(
            test_y,
            test_scores,
            far_target=args.far_target,
        )
        test_at_dev_eer_threshold = _fixed_threshold_metrics(
            test_y,
            test_scores,
            thresholds=dev_thresholds["eer_thresholds"],
            far_target=args.far_target,
            threshold_name="dev_eer_threshold",
            include_frr_at_far=False,
        )
        test_at_dev_far_threshold = _fixed_threshold_metrics(
            test_y,
            test_scores,
            thresholds=dev_thresholds["far_target_thresholds"],
            far_target=args.far_target,
            threshold_name="dev_far_target_threshold",
            include_frr_at_far=True,
        )
        test_by_domain_at_dev_far_threshold = _compute_by_domain_fixed_metrics(
            query_records,
            test_indices,
            test_y,
            test_scores,
            thresholds=dev_thresholds["far_target_thresholds"],
            far_target=args.far_target,
            threshold_name="dev_far_target_threshold",
            include_frr_at_far=True,
        )

        dev_domain_counts = {
            domain: sum(
                1
                for index in dev_indices
                if query_records[index].get("domain") == domain
            )
            for domain in sorted(
                {query_records[index]["domain"] for index in dev_indices}
            )
        }
        test_domain_counts = {
            domain: sum(
                1
                for index in test_indices
                if query_records[index].get("domain") == domain
            )
            for domain in sorted(
                {query_records[index]["domain"] for index in test_indices}
            )
        }

        dev_test_out_path = out_path.with_name(
            f"{out_path.stem}_dev{args.dev_sentences_per_subject}_test_metrics.json"
        )
        dev_test_result = {
            "template_file": str(templates_path),
            "query_feature_dir": str(query_feature_dir),
            "sentence_type": args.sentence_type,
            "domains": sorted(domains),
            "split_seed": int(args.split_seed),
            "dev_sentences_per_subject": int(args.dev_sentences_per_subject),
            "selected_dev_sentence_ids": selected_dev_sentence_ids,
            "num_dev_samples": len(dev_indices),
            "num_test_samples": len(test_indices),
            "dev_domain_counts": dev_domain_counts,
            "test_domain_counts": test_domain_counts,
            "num_subjects": len(subject_ids),
            "embedding_dim": int(embeddings.shape[1]),
            "score_type": "cosine_similarity_query_embedding_to_template",
            "far_target": float(args.far_target),
            "threshold_protocol": (
                "Per-subject one-vs-all thresholds are selected only on "
                "semantic dev sentences and then applied to held-out "
                "semantic test sentences."
            ),
            "dev_thresholds": _metrics_to_jsonable(dev_thresholds),
            "dev_swept": _metrics_to_jsonable(dev_swept_metrics),
            "test_swept_reference": _metrics_to_jsonable(test_swept_metrics),
            "test_at_dev_eer_threshold": _metrics_to_jsonable(
                test_at_dev_eer_threshold
            ),
            "test_at_dev_far_target_threshold": _metrics_to_jsonable(
                test_at_dev_far_threshold
            ),
            "test_by_domain_at_dev_far_target_threshold": _metrics_to_jsonable(
                test_by_domain_at_dev_far_threshold
            ),
        }
        with dev_test_out_path.open("w") as f:
            json.dump(dev_test_result, f, indent=2)
        dev_test_summary_json_path, dev_test_summary_csv_path = _write_summary_files(
            dev_test_out_path,
            overall_metrics=test_at_dev_far_threshold,
            by_domain=test_by_domain_at_dev_far_threshold,
        )
        dev_test_result["metrics_path"] = dev_test_out_path
        dev_test_result["summary_json_path"] = dev_test_summary_json_path
        dev_test_result["summary_csv_path"] = dev_test_summary_csv_path

        if args.global_threshold:
            dev_global_thresholds = _global_swept_metrics(
                dev_y,
                dev_scores,
                far_target=args.far_target,
            )
            global_threshold = dev_global_thresholds["far_target_threshold"]
            test_global_fixed = _global_fixed_threshold_metrics(
                test_y,
                test_scores,
                threshold=global_threshold,
                far_target=args.far_target,
                threshold_name="dev_global_far_target_threshold",
            )
            test_by_domain_global_fixed = _compute_by_domain_global_fixed_metrics(
                query_records,
                test_indices,
                test_y,
                test_scores,
                threshold=global_threshold,
                far_target=args.far_target,
                threshold_name="dev_global_far_target_threshold",
            )

            global_threshold_out_path = out_path.with_name(
                f"{out_path.stem}_dev{args.dev_sentences_per_subject}_"
                "global_threshold_test_metrics.json"
            )
            global_threshold_result = {
                "template_file": str(templates_path),
                "query_feature_dir": str(query_feature_dir),
                "sentence_type": args.sentence_type,
                "domains": sorted(domains),
                "split_seed": int(args.split_seed),
                "dev_sentences_per_subject": int(args.dev_sentences_per_subject),
                "selected_dev_sentence_ids": selected_dev_sentence_ids,
                "num_dev_samples": len(dev_indices),
                "num_test_samples": len(test_indices),
                "dev_domain_counts": dev_domain_counts,
                "test_domain_counts": test_domain_counts,
                "num_subjects": len(subject_ids),
                "embedding_dim": int(embeddings.shape[1]),
                "score_type": "cosine_similarity_query_embedding_to_template",
                "far_target": float(args.far_target),
                "threshold_protocol": (
                    "One global threshold is selected on all semantic dev "
                    "genuine/impostor query-template pairs, then applied to "
                    "all held-out semantic test pairs."
                ),
                "dev_global_thresholds": _metrics_to_jsonable(dev_global_thresholds),
                "test_at_dev_global_far_target_threshold": _metrics_to_jsonable(
                    test_global_fixed
                ),
                "test_by_domain_at_dev_global_far_target_threshold": (
                    _metrics_to_jsonable(test_by_domain_global_fixed)
                ),
            }
            with global_threshold_out_path.open("w") as f:
                json.dump(global_threshold_result, f, indent=2)
            global_summary_json_path, global_summary_csv_path = _write_summary_files(
                global_threshold_out_path,
                overall_metrics=test_global_fixed,
                by_domain=test_by_domain_global_fixed,
            )
            global_threshold_result["metrics_path"] = global_threshold_out_path
            global_threshold_result["summary_json_path"] = global_summary_json_path
            global_threshold_result["summary_csv_path"] = global_summary_csv_path

        if args.domain_specific_thresholds:
            domain_thresholds = {}
            domain_dev_swept = {}
            domain_test_swept = {}
            domain_test_fixed = {}
            threshold_domains = sorted(
                {query_records[index]["domain"] for index in dev_indices}
                & {query_records[index]["domain"] for index in test_indices}
            )

            for domain in threshold_domains:
                dev_domain_positions = _domain_positions(
                    query_records,
                    dev_indices,
                    domain,
                )
                test_domain_positions = _domain_positions(
                    query_records,
                    test_indices,
                    domain,
                )
                domain_dev_y = dev_y[dev_domain_positions]
                domain_dev_scores = dev_scores[dev_domain_positions]
                domain_test_y = test_y[test_domain_positions]
                domain_test_scores = test_scores[test_domain_positions]

                selected_thresholds = _select_dev_thresholds(
                    domain_dev_y,
                    domain_dev_scores,
                    far_target=args.far_target,
                )
                domain_thresholds[domain] = selected_thresholds
                domain_dev_swept[domain] = compute_authentication_metrics(
                    domain_dev_y,
                    domain_dev_scores,
                    far_target=args.far_target,
                )
                domain_test_swept[domain] = compute_authentication_metrics(
                    domain_test_y,
                    domain_test_scores,
                    far_target=args.far_target,
                )
                domain_test_fixed[domain] = _fixed_threshold_metrics(
                    domain_test_y,
                    domain_test_scores,
                    thresholds=selected_thresholds["far_target_thresholds"],
                    far_target=args.far_target,
                    threshold_name=f"dev_{domain}_far_target_threshold",
                    include_frr_at_far=True,
                )

            thresholds_by_domain = {
                domain: payload["far_target_thresholds"]
                for domain, payload in domain_thresholds.items()
            }
            domain_specific_overall = _fixed_domain_specific_threshold_metrics(
                query_records,
                test_indices,
                test_y,
                test_scores,
                thresholds_by_domain=thresholds_by_domain,
                far_target=args.far_target,
                threshold_name="dev_domain_far_target_threshold",
                include_frr_at_far=True,
            )

            domain_specific_out_path = out_path.with_name(
                f"{out_path.stem}_dev{args.dev_sentences_per_subject}_"
                "domain_threshold_test_metrics.json"
            )
            domain_specific_result = {
                "template_file": str(templates_path),
                "query_feature_dir": str(query_feature_dir),
                "sentence_type": args.sentence_type,
                "domains": sorted(domains),
                "split_seed": int(args.split_seed),
                "dev_sentences_per_subject": int(args.dev_sentences_per_subject),
                "selected_dev_sentence_ids": selected_dev_sentence_ids,
                "num_dev_samples": len(dev_indices),
                "num_test_samples": len(test_indices),
                "dev_domain_counts": dev_domain_counts,
                "test_domain_counts": test_domain_counts,
                "num_subjects": len(subject_ids),
                "embedding_dim": int(embeddings.shape[1]),
                "score_type": "cosine_similarity_query_embedding_to_template",
                "far_target": float(args.far_target),
                "threshold_protocol": (
                    "Per-subject one-vs-all thresholds are selected separately "
                    "inside each semantic query domain, using only that domain's "
                    "dev sentences, then applied to that domain's held-out test "
                    "sentences."
                ),
                "domain_thresholds": _metrics_to_jsonable(domain_thresholds),
                "domain_dev_swept": _metrics_to_jsonable(domain_dev_swept),
                "domain_test_swept_reference": _metrics_to_jsonable(domain_test_swept),
                "test_at_dev_domain_far_target_threshold": _metrics_to_jsonable(
                    domain_specific_overall
                ),
                "test_by_domain_at_dev_domain_far_target_threshold": (
                    _metrics_to_jsonable(domain_test_fixed)
                ),
            }
            with domain_specific_out_path.open("w") as f:
                json.dump(domain_specific_result, f, indent=2)
            domain_summary_json_path, domain_summary_csv_path = _write_summary_files(
                domain_specific_out_path,
                overall_metrics=domain_specific_overall,
                by_domain=domain_test_fixed,
            )
            domain_specific_result["metrics_path"] = domain_specific_out_path
            domain_specific_result["summary_json_path"] = domain_summary_json_path
            domain_specific_result["summary_csv_path"] = domain_summary_csv_path

    print(f"Saved metrics: {out_path}")
    print(f"Saved summary: {summary_json_path}")
    print(f"Saved table  : {summary_csv_path}")
    print(f"Queries      : {len(query_records)}")
    print(f"Subjects     : {len(subject_ids)}")
    print(f"Accuracy     : {overall_metrics['accuracy']:.4f}")
    print(f"Macro-F1     : {overall_metrics['macro_f1']:.4f}")
    print(f"Bal. Acc     : {overall_metrics['balanced_accuracy']:.4f}")
    print(f"Top-3 Acc    : {overall_metrics['top3_accuracy']:.4f}")
    print(f"EER          : {overall_metrics['eer']:.4f}")
    print(f"ROC-AUC      : {overall_metrics['roc_auc']:.4f}")
    print(f"FAR          : {overall_metrics['far']:.4f}")
    print(f"FRR          : {overall_metrics['frr']:.4f}")
    if "frr_at_far_1pct" in overall_metrics:
        print(f"FRR@FAR=1%   : {overall_metrics['frr_at_far_1pct']:.4f}")
    print("By mode:")
    for domain in ("normal", "whisper", "silent"):
        if domain not in by_domain:
            continue
        domain_metrics = by_domain[domain]
        print(
            "  "
            f"{domain}: "
            f"acc={domain_metrics['accuracy']:.4f}, "
            f"eer={domain_metrics['eer']:.4f}, "
            f"far={domain_metrics['far']:.4f}, "
            f"frr={domain_metrics['frr']:.4f}"
        )
    if dev_test_result is not None:
        fixed_metrics = dev_test_result["test_at_dev_far_target_threshold"]
        print("Dev/test threshold evaluation:")
        print(f"  Metrics     : {dev_test_result['metrics_path']}")
        print(f"  Summary     : {dev_test_result['summary_json_path']}")
        print(f"  Table       : {dev_test_result['summary_csv_path']}")
        print(f"  Dev samples : {dev_test_result['num_dev_samples']}")
        print(f"  Test samples: {dev_test_result['num_test_samples']}")
        print(f"  Test Acc    : {fixed_metrics['accuracy']:.4f}")
        print(f"  Test EER    : {fixed_metrics['eer']:.4f}")
        print(f"  Test FAR    : {fixed_metrics['far']:.4f}")
        print(f"  Test FRR    : {fixed_metrics['frr']:.4f}")
        if "frr_at_far_1pct" in fixed_metrics:
            print(f"  Test FRR@1% : {fixed_metrics['frr_at_far_1pct']:.4f}")
    if global_threshold_result is not None:
        fixed_metrics = global_threshold_result[
            "test_at_dev_global_far_target_threshold"
        ]
        print("Global threshold evaluation:")
        print(f"  Metrics     : {global_threshold_result['metrics_path']}")
        print(f"  Summary     : {global_threshold_result['summary_json_path']}")
        print(f"  Table       : {global_threshold_result['summary_csv_path']}")
        print(f"  Threshold   : {fixed_metrics['threshold']:.6f}")
        print(f"  Dev samples : {global_threshold_result['num_dev_samples']}")
        print(f"  Test samples: {global_threshold_result['num_test_samples']}")
        print(f"  Test Acc    : {fixed_metrics['accuracy']:.4f}")
        print(f"  Test EER    : {fixed_metrics['eer']:.4f}")
        print(f"  Test FAR    : {fixed_metrics['far']:.4f}")
        print(f"  Test FRR    : {fixed_metrics['frr']:.4f}")
        if "frr_at_far_1pct" in fixed_metrics:
            print(f"  Test FRR@1% : {fixed_metrics['frr_at_far_1pct']:.4f}")
    if domain_specific_result is not None:
        fixed_metrics = domain_specific_result[
            "test_at_dev_domain_far_target_threshold"
        ]
        print("Domain-specific threshold evaluation:")
        print(f"  Metrics     : {domain_specific_result['metrics_path']}")
        print(f"  Summary     : {domain_specific_result['summary_json_path']}")
        print(f"  Table       : {domain_specific_result['summary_csv_path']}")
        print(f"  Dev samples : {domain_specific_result['num_dev_samples']}")
        print(f"  Test samples: {domain_specific_result['num_test_samples']}")
        print(f"  Test Acc    : {fixed_metrics['accuracy']:.4f}")
        print(f"  Test EER    : {fixed_metrics['eer']:.4f}")
        print(f"  Test FAR    : {fixed_metrics['far']:.4f}")
        print(f"  Test FRR    : {fixed_metrics['frr']:.4f}")
        if "frr_at_far_1pct" in fixed_metrics:
            print(f"  Test FRR@1% : {fixed_metrics['frr_at_far_1pct']:.4f}")


if __name__ == "__main__":
    main()
