name: imu_double_feature
batch_size: 32
num_workers: 8
max_epochs: 50
learning_rate: 0.001
weight_decay: 0.0001
device: cuda
seed: 42
input_type: imu_feature_processed
processed_dir: features/imu_te_binaural_lrdiff_200hz_raw9
standardize_features: true
