# @package _global_

train:
  batch_size: 64
  max_epochs: 50
  num_epochs: 50
  learning_rate: 0.0007
  weight_decay: 0.0001
  num_workers: 8
  device: cuda
  name: imu_binaural_tcn_subjects36_nonsemantic_all_ce
  output_dir: outputs/runs/imu/clean/${train.name}
  seed: 42
  input_type: sensor_window_processed
  processed_dir: imu/imu_windows/imu_189_binaural
  preload_windows: true
  sides:
    - binaural
  loss:
    name: cross_entropy

hydra:
  run:
    dir: outputs/runs/imu/clean/${train.name}
