# @package _global_

train:
  batch_size: 32
  max_epochs: 50
  num_epochs: 50
  learning_rate: 0.001
  num_workers: 4
  device: cuda
  name: imu_binaural_resnet_subjects36_nonsemantic_all
  output_dir: outputs/runs/imu/clean/${train.name}
  seed: 42
  input_type: binaural_sensor_window_processed
  processed_dir: imu/imu_windows/imu_189
  preload_windows: true
  sides:
    - left
    - right

hydra:
  run:
    dir: outputs/runs/imu/clean/${train.name}
